### ISSUE TITLE
History corrections

### ISSUE THREAD

**Issue by Coreball** [matthewa313/schedule-sensei#1]
Hi Matthew!

It's great to see the legacy of ScheduleStacker carried on through Schedule Sensei. Thank you for acknowledging my contributions and linking to the original project in the info box, I highly appreciate it. I wrote the first iteration of ScheduleStacker a long time ago, and it was an important step in my CS career.

There are a few things I'd like to make clear on the website. I actually started attending Cornell in 2019, not 2020. The first published version labeled as [ScheduleStacker](https://github.com/Coreball/ScheduleStacker) was written in 2018 with Java, and in 2020 I made [schedulestacker-js](https://github.com/Coreball/schedulestacker-js) in React.

Thanks & good luck with your future endeavors!

**Comment by matthewa313** [comment]
I got you Changyuan! You ought to know that today you're a legend within the walls of the Creek CS room. And I am super inspired Cornell DTI—I often lost my sense of time when I was working on ScheduleSensei. Thank you.

I've updated the info modal; sincere apologies for initial inaccuracies. Please let me know if the updated info modal text is updated to your liking, or request any further edits.

**Comment by Coreball** [comment]
Looks good!
