### ISSUE TITLE
Exporting as CSV 

### ISSUE THREAD

**Issue by ojlennon** [matthewa313/schedule-sensei#3]
![git](https://user-images.githubusercontent.com/45679125/231800761-d1b3580d-eedf-4818-a7eb-ec679e2023dc.png)
![hub](https://user-images.githubusercontent.com/45679125/231800930-b8eb0a6a-4e33-428a-9528-61163a309a3e.png)
Students have noticed an issue with exporting to excel messing up the order of classes. This shows Chamber Orchestra in 3rd period on the website, but 4th in the excel.

Note: Sorry for the email about this. I imagine this is the "cleaner git" you mentioned, Ill be better with this.

**Comment by matthewa313** [comment]
This is fixed in the latest commit.
